---
- name: test task
  copy:
    src: ../docker-compose.yml
    dest: ~/putify/
    # owner: foo
    # group: foo
    # mode: 0644

- name: docker image
  copy:
    src: ../build/puti.tar
    dest: ~/putify/

- name: Load image from archive and push to a private registry
  docker_image:
    name: atonal/puti
    state: present
    force: yes
    load_path: ~/putify/puti.tar

- name: run the service defined in my_project's docker-compose.yml
  docker_service:
    project_src: ~/putify/
